CREATE TABLESPACE tbl_books
DATAFILE 'C:/oraclexe/data/tbl_books.dbf'
SIZE 1M AUTOEXTEND ON NEXT 1K;



CREATE USER one_project IDENTIFIED BY 12341234
DEFAULT TABLESPACE tbl_books;

DROP TABLESPACE tbl_books
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

GRANT DBA TO one_project;